#!/usr/bin/env python3
"""Stage App-bundled voice assets for the local Windows x64 app.

Copies (never links) the receipted runtime build + verified models into
build/voice-assets/, writes build/voice-assets-inventory.json and generates
apps/desktop/bundled-voice-trust.cjs (the compiled trust root; restore it to
null with `git checkout` after packing). Run from the worktree:
  python scripts/win-stage-bundled-assets.py <resources> <build-local-NNN> <faster-whisper-model-dir>
"""
import hashlib, json, shutil, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RES, BUILD, WHISPER = (Path(a).resolve() for a in sys.argv[1:4])
OUT = ROOT / 'build/voice-assets'
INV = ROOT / 'build/voice-assets-inventory.json'
TRUST = ROOT / 'apps/desktop/bundled-voice-trust.cjs'
WHISPER_FILES = {'config.json', 'model.bin', 'tokenizer.json', 'vocabulary.txt'}


def sha(p):
    h = hashlib.sha256()
    with open(p, 'rb') as f:
        for b in iter(lambda: f.read(1 << 20), b''): h.update(b)
    return h.hexdigest()


receipt = json.loads((BUILD / 'receipt.json').read_text(encoding='utf-8'))
rt = BUILD / 'dist/runtime'
files = {p.relative_to(rt).as_posix(): sha(p) for p in sorted(rt.rglob('*')) if p.is_file() and not p.is_symlink()}
if hashlib.sha256(json.dumps(files, sort_keys=True).encode()).hexdigest() != receipt['treeSha256'] or receipt['symlinks'] or receipt['nonPortableNames']:
    sys.exit('runtime build does not match its receipt')
acq = {f['path']: f for f in json.loads((RES / 'acquisition.json').read_text(encoding='utf-8'))['files']}
whisper = {p.name for p in WHISPER.iterdir() if p.is_file()}
if not WHISPER_FILES <= whisper: sys.exit('whisper model incomplete: ' + ','.join(sorted(WHISPER_FILES - whisper)))

if OUT.exists(): shutil.rmtree(OUT)
OUT.mkdir(parents=True)
shutil.copytree(rt, OUT / 'runtime')
(OUT / 'models/kokoro').mkdir(parents=True)
# fp32 model: the fp16 export produces NaN on the CUDA provider (see win-build-local-runtime.py).
pins = {'kokoro-v1.0.onnx': receipt['kokoroFp32'], 'voices-v1.0.bin': acq['kokoro/voices-v1.0.bin']['sha256']}
for name, want in pins.items():
    src = RES / 'kokoro' / name
    if sha(src) != want: sys.exit('kokoro drift ' + name)
    shutil.copy2(src, OUT / 'models/kokoro' / name)
stt_rel = 'models/' + WHISPER.name
(OUT / stt_rel).mkdir(parents=True)
for name in sorted(WHISPER_FILES):  # only the files faster-whisper loads; no HF cache metadata
    shutil.copy2(WHISPER / name, OUT / stt_rel / name)

entries = []
for p in sorted(OUT.rglob('*')):
    if p.is_symlink(): sys.exit('symlink in staged tree: ' + str(p))
    if p.is_file():
        entries.append({'path': p.relative_to(OUT).as_posix(), 'bytes': p.stat().st_size, 'sha256': sha(p)})
entries.sort(key=lambda e: e['path'])  # JS canonicalInventory uses code-unit order; paths are ASCII


def digest(es):
    h = hashlib.sha256()
    for e in es: h.update(f"{e['path']}:{e['bytes']}:{e['sha256']}\n".encode())
    return h.hexdigest()


runtime_entries = sorted(({**e, 'path': e['path'][len('runtime/'):]} for e in entries if e['path'].startswith('runtime/')), key=lambda e: e['path'])
trust = {'schemaVersion': 1, 'treeDigest': digest(entries), 'runtimeTreeDigest': digest(runtime_entries), 'fileCount': len(entries),
         'entrypoint': 'runtime/bin/voice-runtime.exe',
         'roles': {'sttRoot': stt_rel, 'onnxModel': 'models/kokoro/kokoro-v1.0.onnx', 'onnxVoices': 'models/kokoro/voices-v1.0.bin'},
         'source': {'runtimeBuildCommit': receipt['commit'], 'runtimeTreeSha256': receipt['treeSha256'], 'class': receipt['class']}}
INV.write_text(json.dumps({'files': entries}) + '\n', encoding='utf-8')
with open(TRUST, 'w', encoding='utf-8', newline='\n') as f:
    f.write("'use strict';\n// Compiled trust root for App-bundled voice assets. null = this build carries none.\n"
            "// Generated by scripts/win-stage-bundled-assets.py; review the receipt before committing.\n"
            "module.exports = Object.freeze(" + json.dumps(trust, indent=1) + ");\n")
print(json.dumps({'files': len(entries), 'bytes': sum(e['bytes'] for e in entries), 'treeDigest': trust['treeDigest']}))
